
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: opensource-keycloak
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    command: start-dev

volumes:
  postgres-volume: {}

networks:
  default:
    name: opensource_network
