
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: opensource-keycloak
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    command: start-dev

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-volume:/data/db
    container_name: mongodb-container
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "127.0.0.1:27017:27017"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-container
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@mongodb:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - "127.0.0.1:8082:8081"
    restart: always

volumes:
  mongo-volume: {}

networks:
  default:
    name: opensource_network
